-- AIK-08: lược đồ PostgreSQL (theo mục 9 của tài liệu phân tích và thiết kế)
-- Chạy file này trước, sau đó chạy 02_seed.sql.

DROP TABLE IF EXISTS citations, claims, reports, guard_findings, evidence,
    tool_calls, plan_steps, research_sessions, document_chunks, sources, admin_policy CASCADE;

-- Chính sách mặc định do quản trị viên đặt (đúng 1 dòng)
CREATE TABLE admin_policy (
    id                   integer PRIMARY KEY CHECK (id = 1),
    allowlist            text[]  NOT NULL,
    default_max_steps    integer NOT NULL CHECK (default_max_steps > 0),
    default_max_tokens   integer NOT NULL CHECK (default_max_tokens > 0),
    default_max_seconds  integer NOT NULL CHECK (default_max_seconds > 0)
);

-- Danh mục nguồn do quản trị viên đăng ký
CREATE TABLE sources (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          text    NOT NULL CHECK (kind IN ('document', 'api')),
    uri           text    NOT NULL,
    display_name  text    NOT NULL,
    enabled       boolean NOT NULL DEFAULT true
);

-- Kho tài liệu (vector store). Bản demo lưu văn bản; thêm cột embedding vector(...) nếu dùng pgvector.
CREATE TABLE document_chunks (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id  integer NOT NULL REFERENCES sources(id),
    position   integer NOT NULL,
    text       text    NOT NULL,
    UNIQUE (source_id, position)
);

CREATE TABLE research_sessions (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question      text    NOT NULL,
    status        text    NOT NULL CHECK (status IN ('running', 'completed', 'budget_exhausted', 'cancelled', 'error')),
    allowlist     text[]  NOT NULL,
    max_steps     integer NOT NULL,
    max_tokens    integer NOT NULL,
    max_seconds   integer NOT NULL,
    used_steps    integer NOT NULL DEFAULT 0,
    used_tokens   integer NOT NULL DEFAULT 0,
    used_seconds  integer NOT NULL DEFAULT 0,
    started_at    timestamptz NOT NULL DEFAULT now(),
    ended_at      timestamptz,
    end_reason    text,
    -- trạng thái kết thúc phải có thời điểm kết thúc, phiên đang chạy thì không
    CHECK ((status = 'running') = (ended_at IS NULL))
);

CREATE TABLE plan_steps (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  integer NOT NULL REFERENCES research_sessions(id),
    position    integer NOT NULL,
    goal        text    NOT NULL,
    status      text    NOT NULL CHECK (status IN ('pending', 'running', 'done', 'skipped')),
    UNIQUE (session_id, position)
);

CREATE TABLE tool_calls (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      integer NOT NULL REFERENCES research_sessions(id),
    step_id         integer REFERENCES plan_steps(id),
    tool_name       text    NOT NULL,
    arguments       jsonb   NOT NULL DEFAULT '{}'::jsonb,
    outcome         text    NOT NULL CHECK (outcome IN ('ok', 'error', 'blocked')),
    guard_decision  text    NOT NULL CHECK (guard_decision IN ('allowed', 'blocked')),
    guard_reason    text,
    duration_ms     integer NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE evidence (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_call_id  integer NOT NULL REFERENCES tool_calls(id),
    source_id     integer NOT NULL REFERENCES sources(id),
    locator       text    NOT NULL,
    excerpt       text    NOT NULL,
    content_hash  text    NOT NULL,
    retrieved_at  timestamptz NOT NULL DEFAULT now(),
    suspicious    boolean NOT NULL DEFAULT false
);

CREATE TABLE guard_findings (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   integer NOT NULL REFERENCES research_sessions(id),
    tool_call_id integer REFERENCES tool_calls(id),
    evidence_id  integer REFERENCES evidence(id),
    kind         text NOT NULL CHECK (kind IN ('not_allowlisted', 'budget_exceeded', 'injection_suspected', 'unsupported_claim')),
    severity     text NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
    detail       text NOT NULL
);

CREATE TABLE reports (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  integer NOT NULL UNIQUE REFERENCES research_sessions(id),
    body        text    NOT NULL,
    end_reason  text    NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE claims (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id  integer NOT NULL REFERENCES reports(id),
    position   integer NOT NULL,
    text       text    NOT NULL,
    status     text    NOT NULL CHECK (status IN ('sourced', 'unsourced')),
    UNIQUE (report_id, position)
);

CREATE TABLE citations (
    claim_id         integer NOT NULL REFERENCES claims(id),
    evidence_id      integer NOT NULL REFERENCES evidence(id),
    matched_excerpt  text    NOT NULL,
    PRIMARY KEY (claim_id, evidence_id)
);

-- Evidence bất biến sau khi tạo (quy tắc miền ở mục 4)
CREATE OR REPLACE FUNCTION forbid_evidence_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Evidence là bất biến: không được sửa hoặc xóa (id=%)', OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER evidence_immutable
    BEFORE UPDATE OR DELETE ON evidence
    FOR EACH ROW EXECUTE FUNCTION forbid_evidence_change();

-- Khẳng định "có nguồn" phải có ít nhất một citation: kiểm tra bằng view để dễ rà soát
CREATE OR REPLACE VIEW v_claims_without_citation AS
SELECT c.id, c.report_id, c.text
FROM claims c
WHERE c.status = 'sourced'
  AND NOT EXISTS (SELECT 1 FROM citations ci WHERE ci.claim_id = c.id);

-- Vai trò chỉ đọc cho tool (mục 9). Bỏ qua nếu không đủ quyền tạo vai trò.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aik08_tool_reader') THEN
        CREATE ROLE aik08_tool_reader LOGIN PASSWORD 'tool_reader_pw';
    END IF;
    GRANT SELECT ON sources, document_chunks TO aik08_tool_reader;
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'Bỏ qua tạo vai trò chỉ đọc (không đủ quyền).';
END $$;
