IF DB_ID('eSHOPPING_DB') IS NULL CREATE DATABASE eSHOPPING_DB;
GO
USE eSHOPPING_DB;
GO
CREATE TABLE KHACHHANG(
 MaKH INT IDENTITY PRIMARY KEY, HoTen NVARCHAR(100) NOT NULL, NgaySinh DATE NULL,
 CMND VARCHAR(20) NULL, DiaChi NVARCHAR(200) NOT NULL, DienThoai VARCHAR(15) NOT NULL,
 TenDangNhap VARCHAR(50) NOT NULL UNIQUE, MatKhauHash CHAR(64) NOT NULL, Email VARCHAR(100) NULL);
CREATE TABLE NHOMSANPHAM(MaNhom INT IDENTITY PRIMARY KEY, TenNhom NVARCHAR(100) NOT NULL);
CREATE TABLE SANPHAM(
 MaSP VARCHAR(20) PRIMARY KEY, TenSP NVARCHAR(150) NOT NULL, NhaSanXuat NVARCHAR(100),
 MoTa NVARCHAR(MAX), ThongSoKyThuat NVARCHAR(MAX), HinhAnh VARCHAR(200),
 GiaBan DECIMAL(18,0) NOT NULL CHECK(GiaBan>=0), ConHang BIT NOT NULL DEFAULT 1,
 MaNhom INT NOT NULL REFERENCES NHOMSANPHAM(MaNhom));
CREATE TABLE LOAIGIAOHANG(
 MaLoaiGH INT PRIMARY KEY, TenLoai NVARCHAR(60) NOT NULL, DonGia DECIMAL(18,0) NOT NULL,
 NguongMienPhi DECIMAL(18,0) NULL);
CREATE TABLE KHUVUCGIAO(MaKV INT PRIMARY KEY, TenKV NVARCHAR(60) NOT NULL, HeSo DECIMAL(4,2) NOT NULL);
CREATE TABLE LOAITHE(
 MaLoaiThe VARCHAR(10) PRIMARY KEY, TenLoai NVARCHAR(40) NOT NULL,
 SoChuSoThe INT NOT NULL, SoChuSoCSV INT NOT NULL, LePhi DECIMAL(18,0) NOT NULL);
CREATE TABLE DONHANG(
 MaDH INT IDENTITY PRIMARY KEY, MaKH INT NOT NULL REFERENCES KHACHHANG(MaKH),
 NguoiNhan NVARCHAR(100) NOT NULL, DiaChiNhan NVARCHAR(200) NOT NULL, DienThoaiNhan VARCHAR(15) NOT NULL,
 MaLoaiGH INT NOT NULL REFERENCES LOAIGIAOHANG(MaLoaiGH), MaKV INT NOT NULL REFERENCES KHUVUCGIAO(MaKV),
 MaLoaiThe VARCHAR(10) NOT NULL REFERENCES LOAITHE(MaLoaiThe), SoTheMask VARCHAR(25) NOT NULL, TenChuThe NVARCHAR(100) NOT NULL,
 TienHang DECIMAL(18,0) NOT NULL, PhiGiaoHang DECIMAL(18,0) NOT NULL, PhiThe DECIMAL(18,0) NOT NULL,
 TongTri DECIMAL(18,0) NOT NULL, NgayDat DATETIME NOT NULL DEFAULT GETDATE());
CREATE TABLE CHITIETDONHANG(
 MaDH INT NOT NULL REFERENCES DONHANG(MaDH), MaSP VARCHAR(20) NOT NULL REFERENCES SANPHAM(MaSP),
 SoLuong INT NOT NULL CHECK(SoLuong>0), DonGia DECIMAL(18,0) NOT NULL, PRIMARY KEY(MaDH,MaSP));
GO
INSERT NHOMSANPHAM(TenNhom) VALUES(N'Máy ảnh kỹ thuật số'),(N'Đồ chơi'),(N'Thiết bị điện gia dụng'),(N'Thiết bị máy tính');
INSERT SANPHAM VALUES
('CAM01',N'Canon IXUS 185',N'Canon',N'Máy ảnh compact',N'20MP',NULL,3500000,1,1),
('CAM02',N'Sony A6000',N'Sony',N'Mirrorless',N'24MP',NULL,12000000,1,1),
('TOY01',N'Lego City',N'Lego',N'Bộ xếp hình',N'500 chi tiết',NULL,800000,1,2),
('ELE01',N'Nồi chiên không dầu',N'Philips',N'Nồi 4L',N'1500W',NULL,2200000,1,3),
('PC01',N'Chuột Logitech M331',N'Logitech',N'Chuột không dây',N'Silent',NULL,350000,0,4);
INSERT LOAIGIAOHANG VALUES(1,N'Thường',20000,NULL),(2,N'Chuyển phát nhanh',40000,1000000),(3,N'Nhanh trong ngày',80000,5000000);
INSERT KHUVUCGIAO VALUES(1,N'Nội thành',1.0),(2,N'Ngoại thành',1.5),(3,N'Tỉnh khác',2.0);
INSERT LOAITHE VALUES('VISA','VISA',16,3,5000),('MASTER','Mastercard',16,3,5000),('DISCOVER','Discover',16,3,6000),('AMEX','American Express',15,4,9000);
